name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Web Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/web-app:latest ./app

      - name: Build DB Image (optional)
        run: |
          docker pull postgres
          docker tag postgres ghcr.io/${{ github.repository_owner }}/postgres:latest

      - name: Push Images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/web-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/postgres:latest
