name: Build and Push Web + DB Images

on:
  push:
    branches: [ master ]  # Falls du später auf "main" wechselst, hier anpassen

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Web image
      run: |
        docker build -t ghcr.io/leoneub1/assignment3-web:latest ./web
        docker push ghcr.io/leoneub1/assignment3-web:latest

    - name: Build and push DB image
      run: |
        docker build -t ghcr.io/leoneub1/assignment3-db:latest ./db
        docker push ghcr.io/leoneub1/assignment3-db:latest
